import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/landing.tsx"),
  route("signin", "routes/signin.tsx"),
  route("register", "routes/register.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("home", "routes/home.tsx"),
  route("projects", "routes/projects.tsx"), // 301 → /videos
  route("videos", "routes/videos.tsx"),
  route("videos/:id", "routes/videos.$id.tsx"),
  route("templates", "routes/templates.tsx"),
  route("brand", "routes/brand.tsx"),
  route("assets", "routes/assets.tsx"),
  route("team", "routes/team.tsx"),
  route("editor", "routes/editor.tsx"),
  route("export", "routes/export.tsx"),
  route("settings", "routes/settings.tsx"),
  route("pricing", "routes/pricing.tsx"),
  route("checkout", "routes/checkout.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("refund", "routes/refund.tsx"),

  // SEO — use-case landing pages
  route("launch-videos",                "routes/launch-videos.tsx"),
  route("feature-announcement-videos",  "routes/feature-announcement-videos.tsx"),
  route("product-demo-videos",          "routes/product-demo-videos.tsx"),
  route("demo-video-agency-alternative", "routes/demo-video-agency-alternative.tsx"),
  route("saas-explainer-video",          "routes/saas-explainer-video.tsx"),
  route("loom-alternative",              "routes/loom-alternative.tsx"),
  route("synthesia-alternative",         "routes/synthesia-alternative.tsx"),

  // Blog. Posts live in app/lib/blog/posts and appear at their publishAt.
  // Public share links (no login) — app/lib/share.ts
  route("v/:slug",          "routes/v.$slug.tsx"),
  route("v/:slug/download", "routes/v.$slug.download.tsx"),
  route("api/share",        "routes/api.share.tsx"),

  route("blog",       "routes/blog.tsx"),
  route("blog/:slug", "routes/blog.$slug.tsx"),

  // SEO — competitor comparison pages
  route("vs/loom",      "routes/vs.loom.tsx"),
  route("vs/synthesia", "routes/vs.synthesia.tsx"),
  route("vs/runway",    "routes/vs.runway.tsx"),
  route("vs/pictory",   "routes/vs.pictory.tsx"),
  route("vs/veed",      "routes/vs.veed.tsx"),
  route("api/jobs", "routes/api.jobs.tsx"),
  route("api/jobs/:id", "routes/api.jobs.$id.tsx"),
  route("api/shots/:id/retry", "routes/api.shots.$id.retry.tsx"),
  route("api/shots/:id/clip", "routes/api.shots.$id.clip.tsx"),
  route("api/shots/:id/scene-html", "routes/api.shots.$id.scene-html.tsx"),
  route("api/shots/:id/comments", "routes/api.shots.$id.comments.tsx"),
  route("api/shots/:id/assets", "routes/api.shots.$id.assets.tsx"),
  route("api/jobs/:id/stitch", "routes/api.jobs.$id.stitch.tsx"),
  route("api/jobs/:id/export", "routes/api.jobs.$id.export.tsx"),
  route("api/jobs/:id/critique", "routes/api.jobs.$id.critique.tsx"),
  route("api/jobs/:id/improve", "routes/api.jobs.$id.improve.tsx"),
  route("api/jobs/:id/music", "routes/api.jobs.$id.music.tsx"),
  route("api/jobs/:id/sfx", "routes/api.jobs.$id.sfx.tsx"),
  route("api/jobs/:id/assets", "routes/api.jobs.$id.assets.tsx"),
  // Studio (v2) API — docs/studio-v2-contract.md
  route("api/voices/preview", "routes/api.voices.preview.tsx"),
  route("api/studio/jobs", "routes/api.studio.jobs.tsx"),
  route("api/studio/videos", "routes/api.studio.videos.tsx"),
  route("api/studio/videos/:id", "routes/api.studio.videos.$id.tsx"),
  route("api/studio/videos/:id/duplicate", "routes/api.studio.videos.$id.duplicate.tsx"),
  route("api/studio/templates", "routes/api.studio.templates.tsx"),
  route("api/studio/templates/:id/use", "routes/api.studio.templates.$id.use.tsx"),
  route("api/studio-libs/*", "routes/api.studio-libs.$.tsx"),
  // Cron keep-alive from src/worker.ts while Studio tasks are pending.
  route("api/internal/worker-ping", "routes/api.internal.worker-ping.tsx"),
  route("api/jobs/:id/edit", "routes/api.jobs.$id.edit.tsx"),
  route("api/jobs/:id/regenerate", "routes/api.jobs.$id.regenerate.tsx"),
  route("api/jobs/:id/revert", "routes/api.jobs.$id.revert.tsx"),
  route("api/jobs/:id/document", "routes/api.jobs.$id.document.tsx"),
  route("api/jobs/:id/timeline", "routes/api.jobs.$id.timeline.tsx"),
  route("api/jobs/:id/render", "routes/api.jobs.$id.render.tsx"),
  route("api/jobs/:id/download", "routes/api.jobs.$id.download.tsx"),
  route("api/brand-kit", "routes/api.brand-kit.tsx"),
  route("api/assets", "routes/api.assets.tsx"),
  route("api/assets/:id", "routes/api.assets.$id.tsx"),
  route("api/me/usage", "routes/api.me.usage.tsx"),
  route("api/brand/logo", "routes/api.brand.logo.tsx"),
  route("api/reference-video", "routes/api.reference-video.tsx"),
  route("api/brand/scrape", "routes/api.brand.scrape.tsx"),
  route("api/music/search", "routes/api.music.search.tsx"),
  route("api/sfx/search", "routes/api.sfx.search.tsx"),
  route("api/auth/signout", "routes/api.auth.signout.tsx"),
  route("api/auth/forgot-password", "routes/api.auth.forgot-password.tsx"),
  route("api/auth/reset-password", "routes/api.auth.reset-password.tsx"),
  // Backoffice admin panel (gated by ADMIN_EMAILS; served at backoffice.videly.io)
  route("backoffice", "routes/backoffice.tsx"),
  route("backoffice/users/:id", "routes/backoffice.users.$id.tsx"),
  route("backoffice/share", "routes/backoffice.share.tsx"),
  route("backoffice/videos", "routes/backoffice.videos.tsx"),
  route("backoffice/videos/:id", "routes/backoffice.videos.$id.tsx"),
  route("api/backoffice/impersonate", "routes/api.backoffice.impersonate.tsx"),
  route("impersonate/start", "routes/impersonate.start.tsx"),
  route("impersonate/stop", "routes/impersonate.stop.tsx"),

  route("api/billing/checkout", "routes/api.billing.checkout.tsx"),
  route("api/billing/cancel-subscription", "routes/api.billing.cancel-subscription.tsx"),
  route("api/billing/change-plan", "routes/api.billing.change-plan.tsx"),
  route("api/webhooks/polar", "routes/api.webhooks.polar.tsx"),
  route("api/webhooks/dodo", "routes/api.webhooks.dodo.tsx"),
  route("sitemap.xml", "routes/sitemap.tsx"),
] satisfies RouteConfig;
