import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/landing.tsx"),
  route("signin", "routes/signin.tsx"),
  route("register", "routes/register.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("home", "routes/home.tsx"),
  route("projects", "routes/projects.tsx"),
  route("editor", "routes/editor.tsx"),
  route("export", "routes/export.tsx"),
  route("settings", "routes/settings.tsx"),
  route("pricing", "routes/pricing.tsx"),
  route("checkout", "routes/checkout.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("api/jobs", "routes/api.jobs.tsx"),
  route("api/jobs/:id", "routes/api.jobs.$id.tsx"),
  route("api/shots/:id/retry", "routes/api.shots.$id.retry.tsx"),
  route("api/shots/:id/clip", "routes/api.shots.$id.clip.tsx"),
  route("api/shots/:id/scene-html", "routes/api.shots.$id.scene-html.tsx"),
  route("api/shots/:id/comments", "routes/api.shots.$id.comments.tsx"),
  route("api/shots/:id/assets", "routes/api.shots.$id.assets.tsx"),
  route("api/jobs/:id/stitch", "routes/api.jobs.$id.stitch.tsx"),
  route("api/jobs/:id/export", "routes/api.jobs.$id.export.tsx"),
  route("api/jobs/:id/critique", "routes/api.jobs.$id.critique.tsx"),
  route("api/jobs/:id/improve", "routes/api.jobs.$id.improve.tsx"),
  route("api/jobs/:id/music", "routes/api.jobs.$id.music.tsx"),
  route("api/jobs/:id/sfx", "routes/api.jobs.$id.sfx.tsx"),
  route("api/jobs/:id/assets", "routes/api.jobs.$id.assets.tsx"),
  route("api/brand/logo", "routes/api.brand.logo.tsx"),
  route("api/brand/scrape", "routes/api.brand.scrape.tsx"),
  route("api/music/search", "routes/api.music.search.tsx"),
  route("api/sfx/search", "routes/api.sfx.search.tsx"),
  route("api/auth/signout", "routes/api.auth.signout.tsx"),
  route("api/auth/forgot-password", "routes/api.auth.forgot-password.tsx"),
  route("api/auth/reset-password", "routes/api.auth.reset-password.tsx"),
  route("api/billing/customer", "routes/api.billing.customer.tsx"),
  route("api/billing/cancel-subscription", "routes/api.billing.cancel-subscription.tsx"),
  route("api/webhooks/paddle", "routes/api.webhooks.paddle.tsx"),
  route("sitemap.xml", "routes/sitemap[.]xml.tsx"),
] satisfies RouteConfig;
